# GitHub Action for generating a contribution graph with a snake eating your contributions.

name: Generate Snake
on:
  schedule:
    - cron: "0 */6 * * *" # every 6 hours
  workflow_dispatch: # Run the Action automatically from the Actions tab

jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve repository
        uses: actions/checkout@v3
      - name: Generate the snake
        uses: Platane/snk@v3.1
        id: snake-gif
        with:
          github_user_name: Tao-Galasse
          # these next 2 lines generate the files on a branch called "output". This keeps the main branch from cluttering up
          outputs: |
            dist/github-contribution-grid-snake.gif
            dist/github-contribution-grid-snake.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: git status # show the status of the build. Makes it easier for debugging (if there's any issues)
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true
      - uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output # the output branch mentioned above
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
